// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnymxttwcjqnhlznqmhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpueW14dHR3Y2pxbmhsem5xbWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzY2MjMsImV4cCI6MjA2ODAxMjYyM30.nZlXT7Qd-_xDhDSBCDBsgGkPtXZ07D6ZBnuoVETXb20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});